### ISSUE TITLE
[Bug]: Streamlit txt2vid fails with RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by cstueckrath** [sd-webui/stable-diffusion-webui#1047]
### What happened?

Generation generally fails.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Relevant log output

```shell
Tx2Vid Model Loaded
2022-09-12 09:12:01.214 Uncaught app exception
Traceback (most recent call last):
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/home/cstueckrath/rocm/stable-diffusion-webui/scripts/webui_streamlit.py", line 2516, in <module>
    layout()
  File "/home/cstueckrath/rocm/stable-diffusion-webui/scripts/webui_streamlit.py", line 2462, in layout
    image, seed, info= txt2vid(prompts=prompt, gpu=defaults.general.gpu,
  File "/home/cstueckrath/rocm/stable-diffusion-webui/scripts/webui_streamlit.py", line 1874, in txt2vid
    cond_embeddings = st.session_state["pipe"].text_encoder(text_input.input_ids.to(torch_device))[0] # shape [1, 77, 768]
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 722, in forward
    return self.text_model(
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cstueckrath/anaconda3/envs/lsd/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudumaroja** [comment]
i guess this is a problem if you have to use --no-half --precision full but then i guess you will have to live with green squares
