### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'transformers' error, on Centos 7

### ISSUE THREAD

**Issue by vfyang** [sd-webui/stable-diffusion-webui#1168]
### What happened?

Failed to launch webUI;
command line:
python -v scripts/webui.py --no-half --precision=full

the code broke with these errors:
.....
import 'ldm.modules.encoders' # <_frozen_importlib_external.SourceFileLoader object at 0x7f41f6ce6f70>
# /root/sd-web/stable-diffusion-webui/ldm/modules/encoders/__pycache__/modules.cpython-38.pyc matches /root/sd-web/stable-diffusion-webui/ldm/modules/encoders/modules.py
# code object from '/root/sd-web/stable-diffusion-webui/ldm/modules/encoders/__pycache__/modules.cpython-38.pyc'
Traceback (most recent call last):
  File "scripts/webui.py", line 453, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 444, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 150, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/sd-web/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/root/sd-web/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/root/anaconda3/envs/lsd/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sd-web/stable-diffusion-webui/ldm/modules/encoders/modules.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers'
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
.....

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
#a cloud server V100,
# update the CUDA dirver:
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
```

### Relevant log output

```shell
.....
import 'ldm.modules.encoders' # <_frozen_importlib_external.SourceFileLoader object at 0x7f41f6ce6f70>
# /root/sd-web/stable-diffusion-webui/ldm/modules/encoders/__pycache__/modules.cpython-38.pyc matches /root/sd-web/stable-diffusion-webui/ldm/modules/encoders/modules.py
# code object from '/root/sd-web/stable-diffusion-webui/ldm/modules/encoders/__pycache__/modules.cpython-38.pyc'
Traceback (most recent call last):
  File "scripts/webui.py", line 453, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 444, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 150, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/sd-web/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/root/sd-web/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/sd-web/stable-diffusion-webui/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/root/anaconda3/envs/lsd/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/sd-web/stable-diffusion-webui/ldm/modules/encoders/modules.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers'
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
.....
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vfyang** [comment]
Fixed by :
pip install transformers

It would be nice if this could be part of the linux setup script.

Thanks.

**Comment by hlky** [comment]
> It would be nice if this could be part of the linux setup script.

It is. All the dependencies are listed in the environment.yaml file and they are installed when you create the environment.
