### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kallamamran** [sd-webui/stable-diffusion-webui#1218]
### What happened?

Trying to get the textual inversion training to run, but I run in to a problem that doesn't seem to be listed anywhere and I can't figure out what's wrong.

1. Copy the files to get textual inversion to work 👍
2. Copy a maximum of 5 images of the object I want to train on in the size 512x512 to an empty folder 👍
3. Run:
python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n kallamamran --data_root d:\TRAIN --gpus 1 --init-word kallamamran 👎

**I get this error:**
_yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\stable-diffusion-main\configs\stable-diffusion\v1-finetune.yaml", line 28, column 66_

Don't know what to do about that. Have looked into the v1-finetune.yaml on line 28 and it's a veeeery long line 😲

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Global seed set to 23
Traceback (most recent call last):
  File "main.py", line 514, in <module>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "main.py", line 514, in <listcomp>
    configs = [OmegaConf.load(cfg) for cfg in opt.base]
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\omegaconf\omegaconf.py", line 184, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Kallamamran\anaconda3\envs\ldm\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\stable-diffusion-main\configs\stable-diffusion\v1-finetune.yaml", line 28, column 66
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Perhaps you should ask for support in the project where you got that script, you did not get it from here, I was not involved with its creation.

**Comment by Kallamamran** [comment]
Shit... This Github-stuff is so messed up. I have no structure 😂 Sorry for the messup!!

**Comment by hlky** [comment]
`python main.py`

`stable-diffusion-main\configs\stable-diffusion`

You didn't get the training script from here. That folder isn't even the name of the folder from this repo.

The files in the `sd-enable-textual-inversion` repo do not include the training script.

Perhaps you should ask for support in the project where you got that script, you did not get it from here, I was not involved with its creation.

**Comment by Kallamamran** [comment]
I was certain I did... Sorry
