### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'k_diffusion'

### ISSUE THREAD

**Issue by Nitrobacters** [sd-webui/stable-diffusion-webui#1239]
### What happened?

Hello,

Followed this instruction : https://sd-webui.github.io/stable-diffusion-webui/docs/1.installation.html

when I run webui.cmd I have :
```
Traceback (most recent call last):
  File "scripts/webui.py", line 61, in <module>
    import k_diffusion as K
ModuleNotFoundError: No module named 'k_diffusion'

```
I'm running SD on Windows 11 with AMD CPU and NVIDIA GPU.

I can see the k-diffusion v0.0.1 in the ldm module list.

I tried with miniconda, anaconda and both, and to change ldm to ldo.

I also tried before to remove the z-version-env.tmp file, the ldm env and the src folder I have the same error.

Thx.

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Environment name is set as ldm as per environment.yaml
anaconda3/miniconda3 detected in C:\Users\Arthur\miniconda3
Stashing local changes and pulling latest update...
No local changes to save
Already up to date.
Do you want to restore changes you made before updating? (Y/N): n
Removing changes please wait...
No stash entries found.
Changes removed, press any key to continue...
Current  environment.yaml hash: 148c41826b9b55a6387ca46625329da99cb75dc8
Previous environment.yaml hash: 148c41826b9b55a6387ca46625329da99cb75dc8
environment.yaml unchanged. dependencies should be up to date.
if you still have unresolved dependencies, delete "z_version_env.tmp"
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 61, in <module>
    import k_diffusion as K
ModuleNotFoundError: No module named 'k_diffusion'
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 1
Relauncher: Launching...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nitrobacters** [comment]
Ok..
I install manualy all the dependencies and it work..
Sorry for the inconvenience.
