### ISSUE TITLE
[Bug]: Copy full parameters in img2img broken

### ISSUE THREAD

**Issue by xaedes** [sd-webui/stable-diffusion-webui#1299]
### What happened?

Copying the full parameters from output info of img2img does not work.
This is due to my fix (#1289) for the highlighting of the output info.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Uncaught (in promise) TypeError: x.replace is not a function
    at eval (eval at <anonymous> (index.c16c72cb.js:6412:21), <anonymous>:3:61)
    at eval (eval at <anonymous> (index.c16c72cb.js:6412:21), <anonymous>:3:81)
    at index.c16c72cb.js:7763:26
    at HTMLButtonElement.<anonymous> (index.c16c72cb.js:6567:18)
    at index.c16c72cb.js:527:44
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.bubble (index.c16c72cb.js:527:27)
    at HTMLButtonElement.click_handler (index.c11d742f.js:213:10)
    at index.c16c72cb.js:527:44
    at Array.forEach (<anonymous>)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xaedes** [comment]
There is also an bug logged into the console when using "Copy full parameters" in txt2img, but it works anyway.
Here is the console output when clicking the button:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at handle_update (index.c16c72cb.js:6587:18)
```
