### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yangboz** [sd-webui/stable-diffusion-webui#1330]
### What happened?

 File "stable-diffusion-webui/scripts/webui_streamlit.py", line 5, in <module>
    import streamlit_nested_layout
ModuleNotFoundError: No module named 'streamlit_nested_layout'

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
py3.7
ubuntu20.04
```

### Relevant log output

```shell
Starting Stable Diffusion WebUI: Streamlit Interface. Please Wait...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.5.121:8501
  External URL: http://222.240.1.31:8501

2022-09-27 09:42:04.018 Uncaught app exception
Traceback (most recent call last):
  File "/home/xibaoda/anaconda3/envs/py37/lib/python3.7/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/home/xibaoda/Linux-StableDiffusion-Script-main/stable-diffusion-webui/scripts/webui_streamlit.py", line 5, in <module>
    import streamlit_nested_layout
ModuleNotFoundError: No module named 'streamlit_nested_layout'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangboz** [comment]
and fixed with  other missing pips as following:

```
pip install streamlit-nested-layout
```
```
pip install streamlit-on-Hover-tabs
```
```
pip install git+https://github.com/crowsonkb/k-diffusion/
```
hope it helps .
