### ISSUE TITLE
[Bug]: I get this error when i try to use the WebUI

### ISSUE THREAD

**Issue by GiannisKotzavasileiou** [sd-webui/stable-diffusion-webui#1340]
### What happened?

I have edited the Webui-user.bat to skip the Cuda test so the Webui opens but i can't make it work. This is what the cmd gives me as an error!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --skip-torch-cuda-test 
call webui.bat
```

### Relevant log output

```shell
txt2img:

Error completing request

Arguments: ('', '', 'None', 'None', 20, 6, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 64, 64, False, False, 0.7, 0, False, None, '', False, 1, '', 4, '', True, False) {}

Traceback (most recent call last):

File "E:\stable diffusion\stable-diffusion-webui\modules\ui.py", line 136, in f

res = list(func(*args, **kwargs))

File "E:\stable diffusion\stable-diffusion-webui\webui.py", line 60, in f

res = func(*args, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\modules\txt2img.py", line 41, in txt2img

processed = process_images(p)

File "E:\stable diffusion\stable-diffusion-webui\modules\processing.py", line 333, in process_images

uc = prompt_parser.get_learned_conditioning(len(prompts) * [p.negative_prompt], p.steps)

File "E:\stable diffusion\stable-diffusion-webui\modules\prompt_parser.py", line 104, in get_learned_conditioning

conds = shared.sd_model.get_learned_conditioning(texts)

File "E:\stable diffusion\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 558, in get_learned_conditioning

c = self.cond_stage_model(c)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\modules\sd_hijack.py", line 374, in forward

outputs = self.wrapped.transformer(input_ids=tokens)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward

return self.text_model(

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward

encoder_outputs = self.encoder(

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward

layer_outputs = encoder_layer(

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 316, in forward

hidden_states = self.layer_norm1(hidden_states)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl

return forward_call(*input, **kwargs)

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 189, in forward

return F.layer_norm(

File "E:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2503, in layer_norm

return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)

RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Wrong project
