### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by maikelsz** [sd-webui/stable-diffusion-webui#1376]
### What happened?

I have the "Stable Difusion UI" project running, but now I want "Stable Difussion WebUI" too. after struggling a little I manage to make it start. but is not working. have some error

System: Windows 10
Web browser: Firefox

I don´t have an NVIDIA GPU, so I add --skip-torch-cuda-test  to the COMMANDLINE_ARGS, on launch.py file, just like this: 
commandline_args = os.environ.get('COMMANDLINE_ARGS', "--skip-torch-cuda-test")
please, correct me if I did it wrong

after ask for an image,  on the web interface it says: 
"RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'"

I add the full console text below:

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
all defaults. I just input some text to test if I was installed OK
```

### Relevant log output

```shell
full console log, from start to error:


venv "F:\stable-diffusion-webui\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.8.4rc1 (tags/v3.8.4rc1:6c38841, Jun 30 2020, 15:17:30) [MSC v.1924 64 bit (AMD64)]
Commit hash: 2b03f0bbda1229dff6e7ab6f656b28587eba8308
Installing requirements for Web UI
Launching Web UI with arguments:
Warning: LDSR not found at path F:\stable-diffusion-webui\stable-diffusion-webui\repositories\latent-diffusion\LDSR.py
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [7460a6fa] from F:\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Global Step: 470000
Model loaded.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

txt2img: dog eating a bone
Loaded a total of 0 textual inversion embeddings.
Error completing request
Arguments: ('dog eating a bone', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, False, 0.7, 0, False, False, None, '', 1, '', 4, '', True, False) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\stable-diffusion-webui\modules\ui.py", line 153, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\stable-diffusion-webui\webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\modules\txt2img.py", line 41, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\modules\processing.py", line 351, in process_images
    uc = prompt_parser.get_learned_conditioning(len(prompts) * [p.negative_prompt], p.steps)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\modules\prompt_parser.py", line 104, in get_learned_conditioning
    conds = shared.sd_model.get_learned_conditioning(texts)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 558, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_hijack.py", line 495, in forward
    outputs = self.wrapped.transformer(input_ids=tokens)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 316, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 189, in forward
    return F.layer_norm(
  File "F:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
This is not the project you have installed.
