### ISSUE TITLE
[Bug]: No module named 'loguru'

### ISSUE THREAD

**Issue by emeraldminer299** [sd-webui/stable-diffusion-webui#1438]
### What happened?

So, for starters, I haven't used Stable Diffusion WebUI since a month ago. Anyways I changed LDM to LDO since it for some reason didn't keep environment changes specifically.

I installed loguru just to see and still no luck.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
optimized_turbo = True

--no-half --precision full
```

### Relevant log output

```shell
Relauncher: Launching...
Traceback (most recent call last):
  File "C:\Users\######\stable-diffusion-webui\scripts\webui.py", line 20, in <module>
    from logger import logger, set_logger_verbosity, quiesce_logger
  File "C:\Users\######\stable-diffusion-webui\scripts\logger.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emeraldminer299** [comment]
I did say yes. It was just a one off thing where it specifically forgot the
environment file. It doesn’t do it now.
