### ISSUE TITLE
[Bug]: KeyError: 'st.session_state has no key "GFPGAN_model"

### ISSUE THREAD

**Issue by dineshdharme** [sd-webui/stable-diffusion-webui#1453]
### What happened?

A bug happened!

KeyError: 'st.session_state has no key "GFPGAN_model". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
No custom settings.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/vivek/anaconda3/envs/ldm/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/mnt/stabilitydiffusion/hlky-webui-starting/stable-diffusion-webui/scripts/webui_streamlit.py", line 177, in <module>
    layout()
  File "/mnt/stabilitydiffusion/hlky-webui-starting/stable-diffusion-webui/scripts/webui_streamlit.py", line 141, in layout
    layout()
  File "scripts/txt2img.py", line 406, in layout
    use_GFPGAN=st.session_state["use_GFPGAN"], GFPGAN_model=st.session_state["GFPGAN_model"] ,
  File "/home/vivek/anaconda3/envs/ldm/lib/python3.8/site-packages/streamlit/runtime/state/session_state_proxy.py", line 93, in __getitem__
    return get_session_state()[key]
  File "/home/vivek/anaconda3/envs/ldm/lib/python3.8/site-packages/streamlit/runtime/state/safe_session_state.py", line 111, in __getitem__
    return self._state[key]
  File "/home/vivek/anaconda3/envs/ldm/lib/python3.8/site-packages/streamlit/runtime/state/session_state.py", line 440, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "GFPGAN_model". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
try clearing userconfig in configs/webui

**Comment by dineshdharme** [comment]
no effect. still same error.

**Comment by brian000** [comment]
I had the same issue with a clean install.  In the UI, I was able to go to Model Manager and hit the download button for GFPGAN to fix it.

**Comment by dineshdharme** [comment]
yeah that worked.

**Comment by chrisbigelow** [comment]
Seeing the same issue. How do I navigate to Model Manager?

**Comment by PrivateGER** [comment]
> Seeing the same issue. How do I navigate to Model Manager?

Launch the Streamlit webui, it's one of the options in the hamburger menu on the left.
