### ISSUE TITLE
[Bug]: Upscaler selection missing in latest update

### ISSUE THREAD

**Issue by LegoAdrian** [sd-webui/stable-diffusion-webui#1460]
### What happened?

The latest update broke the upscaler selection menu on my pc. The selection buttons have disapeared for selecting the GoBig upscaler and real-esrgan 2/4/anime selection. When I click Process, it returns an error:

```
Processing images...
Loaded RealESGAN
Couldn't find metadata on image
Couldn't find metadata on image
Traceback (most recent call last):
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\afsw7\miniconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 2256, in imgproc
    image = processRealESRGAN(image)
  File "scripts/webui.py", line 1964, in processRealESRGAN
    RealESRGAN = load_RealESRGAN(modelMode)
  File "scripts/webui.py", line 415, in load_RealESRGAN
    raise Exception(model_name+".pth not found at path "+model_path)
Exception: RealESRGAN_x4plus.pth not found at path ./RealESRGAN\RealESRGAN_x4plus.pth
```

It was working previously on my system, and I have confirmed the upscaler files are still present.

PC: Windows 11, 11700k, RTX 3060

Screenshot:
drive.google.com/file/d/18jzNl9E5uJk2uUcIJI13R4aEG6hgqV35/view?usp=sharing

There is nothing else below this.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jokkebk** [comment]
Based on the latest documentation, the models seem to be under new directories, looking under models/ldsr, models/gfpgan etc. when earlier it was src/latent-diffusion/experiments/pretrained_models etc.

However, at least on Windows, it tried to open ./models/ldsr\model.cpkt (note the \ vs. / clash) without success, and GFPGAN was looked in ./GFPGAN\GFPGANv1.3.pth (while docs say it should go under models/GFPGAN).

Based on cursory look, I guess someone changed the paths but docs haven't quite kept up, and might be that Windows paths got broken as well.
