### ISSUE TITLE
[Bug]: Application Crash: ConnectionResetError: An existing connection was forcibly closed by remote host

### ISSUE THREAD

**Issue by Al00X** [sd-webui/stable-diffusion-webui#1477]
### What happened?

**Streamlit** version.

After keeping stable diffusion in the background (idle state), these errors suddenly with no reason pop on my terminal repeatedly like it goes in some kind of a dead loop. Eventually application is crashed and it should be restarted.

![image](https://user-images.githubusercontent.com/12069672/194701669-7b461d3d-75bb-421a-a107-a664f423b580.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
2022-10-08 13:21:37.621 Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\_\.conda\envs\ldm\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\_\.conda\envs\ldm\lib\asyncio\selector_events.py", line 120, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muunkky** [comment]
I'm having what seems to be the same problem.
@Al00X were you able to find a fix?

`Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\_\Cameron\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`

**Comment by cclcng** [comment]
also having this issue

**Comment by zdoek001** [comment]
Same issue

**Comment by zdoek001** [comment]
> Same issue 同样的问题

追加:
有可能是 ADetailer 拓展导致的,下载了它缺失的模型后,正常了
