### ISSUE TITLE
[Bug]: Text-to-Video 'setIn' cannot be called on an ElementNode

### ISSUE THREAD

**Issue by Delivator** [sd-webui/stable-diffusion-webui#1499]
### What happened?

Trying to generate a video with Text-to-Video it throws me the error `'setIn' cannot be called on an ElementNode` and `OSError: You need a huggingface token in order to use the Text to Video tab. Use the Settings page from the sidebar on the left to add your token.` even though I added the huggingface token to the `userconfig_streamlit.yaml` file.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Delivator\miniconda3\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Delivator\stable-diffusion-webui\scripts\webui_streamlit.py", line 177, in <module>
    layout()
  File "C:\Users\Delivator\stable-diffusion-webui\scripts\webui_streamlit.py", line 149, in layout
    layout()
  File "scripts\txt2vid.py", line 883, in layout
    video, seed, info, stats = txt2vid(prompts=prompt, gpu=st.session_state["defaults"].general.gpu,
  File "scripts\txt2vid.py", line 421, in txt2vid
    load_diffusers_model(weights_path, torch_device)
  File "scripts\txt2vid.py", line 269, in load_diffusers_model
    raise OSError("You need a huggingface token in order to use the Text to Video tab. Use the Settings page from the sidebar on the left to add your token.")
OSError: You need a huggingface token in order to use the Text to Video tab. Use the Settings page from the sidebar on the left to add your token.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kimlage** [comment]
I'm having this exact problem in but in Linux

**Comment by vacuumn** [comment]
Same here, 
Windows, Chrome

**Comment by DRSteven** [comment]
I have the same when going to the model manager and trying to download "STable Diffusion V1.5" on windows, chrome
