### ISSUE TITLE
[Bug]: Latent Diffusion and GoLatent aren't working properly

### ISSUE THREAD

**Issue by HenkDz** [sd-webui/stable-diffusion-webui#560]
### What happened?

I've update the to the latest version and configured LDSR properly but when I send an image to lab and try to upscale with either Laten Diffusion or GoLatent, it throws an error.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Where are you running the webui?

Windows

### Relevant log output

```shell
Processing images...
Unloaded Stable Diffusion
Unloaded GFPGAN
Loaded LDSR
Traceback (most recent call last):
  File "E:\a3\envs\ldm\lib\site-packages\gradio\routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 643, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 558, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "webui.py", line 1839, in imgproc
    image = processLDSR(image)
  File "webui.py", line 1766, in processLDSR
    result = LDSR.superResolution(image,int(imgproc_ldsr_steps),str(imgproc_ldsr_pre_downSample),str(imgproc_ldsr_post_downSample))
  File "E:\a3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\a3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "e:\a3\sdwebui\src\latent-diffusion\LDSR.py", line 315, in superResolution
    model = self.load_model_from_config()
  File "e:\a3\sdwebui\src\latent-diffusion\LDSR.py", line 76, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "e:\a3\sdwebui\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
TypeError: __init__() missing 1 required positional argument: 'personalization_config'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdBarho** [comment]
@HenkDz are you also using textual invesion?

**Comment by HenkDz** [comment]
> @HenkDz are you also using textual inversion?

Yes I am.

**Comment by HenkDz** [comment]
> @HenkDz are you also using textual inversion?

Disabling it seems to have solved the issue.

**Comment by AbdBarho** [comment]
I had the same problem, I had to rename the models / import and hack my way around it

See [here](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/build/Dockerfile#L50) and [here](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/build/mount.sh#L25)

**Comment by HenkDz** [comment]
> I had the same problem, I had to rename the models / import and hack my way around it
> 
> See [here](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/build/Dockerfile#L50) and [here](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/build/mount.sh#L25)

Thanks mate. I don't really need text inversion, so I'm good for now till they push a fix for it. Appreciate your help.
