### ISSUE TITLE
[Bug]: Latent Diffusion and GoLatent don't work for me anymore

### ISSUE THREAD

**Issue by lashmanRB** [sd-webui/stable-diffusion-webui#589]
### What happened?

everything worked fine when the Image Lab was pushed to main the first time around, but for the last few updates i'm just getting this error whenever i try to use those two

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
none
```

### Relevant log output

```shell
Processing images...
Unloaded Stable Diffusion
Loaded LDSR
Traceback (most recent call last):
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1856, in imgproc
    image = processLDSR(image)
  File "scripts/webui.py", line 1783, in processLDSR
    result = LDSR.superResolution(image,int(imgproc_ldsr_steps),str(imgproc_ldsr_pre_downSample),str(imgproc_ldsr_post_downSample))
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Software\miniconda3\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: superResolution() takes 2 positional arguments but 5 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dalmackay** [comment]
same here but for GoBig. TypeError: imgproc() takes 14 positional arguments but 17 were given

**Comment by lashmanRB** [comment]
> same here but for GoBig. TypeError: imgproc() takes 14 positional arguments but 17 were given

whew, i'm glad it's not just me then

**Comment by devilismyfriend** [comment]
Read the notice in the Readme
