### ISSUE TITLE
[Bug]: RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by LiJT** [sd-webui/stable-diffusion-webui#612]
### What happened?

The following error msg occurs when I decide to upscale my image

Processing images...
Traceback (most recent call last):
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1855, in imgproc
    image = processLDSR(image)
  File "scripts/webui.py", line 1782, in processLDSR
    result = LDSR.superResolution(image,int(imgproc_ldsr_steps),str(imgproc_ldsr_pre_downSample),str(imgproc_ldsr_post_downSample))
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-main\src\latent-diffusion\LDSR.py", line 315, in superResolution
    model = self.load_model_from_config()
  File "E:\stable-diffusion-main\src\latent-diffusion\LDSR.py", line 72, in load_model_from_config
    pl_sd = torch.load(self.modelPath, map_location="cpu")
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\charl\miniconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

![1](https://user-images.githubusercontent.com/11270197/188300067-346c1cca-97fb-4011-bd38-be85a182f5aa.png)

As long as I go with Latent Diffusion SR upscale model, this error occurs, Could anyone tell me where i did wrong? I follow the exact procedure as followed

> Git clone https://github.com/devilismyfriend/latent-diffusion into your stable-diffusion-main/src/ folder
Rename latent-diffusion-main folder to latent-diffusion
If on windows: run download_models.bat to download the required model files
Otherwise to manually install the model download [project.yaml](https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1) and [last.cpkt](https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1) and rename last.ckpt to model.ckpt
Place both under stable-diffusion-main/src/latent-diffusion/experiments/pretrained_models/
Make sure you have both project.yaml and model.ckpt in that folder and path.
LDSR should be wokring now.

Please help me, thank you!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChristopheHolmes** [comment]
Hi, I had the same error because of a partialy downloaded model (the latent-diffusion one).

You should check the size of the file to be sure
