### ISSUE TITLE
[Bug]: x, mask = x["image"], x["mask"]

### ISSUE THREAD

**Issue by TristanMorelle** [sd-webui/stable-diffusion-webui#664]
### What happened?

this error is back again when uncropping, gets fixed when switching to mask and back i think

Traceback (most recent call last):
  File "...\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "...\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "...\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "...\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NicholasCureton** [comment]
Me2

**Comment by zweifuchs** [comment]
Same problem. Fresh install/build a couple of hours ago.

**Comment by codedealer** [comment]
try this branch https://github.com/hlky/stable-diffusion-webui/tree/img2img-fix

**Comment by snarkipus** [comment]
@codedealer That seems to have resolved it - I just manually patched the files, though vs. trying to sort out how to pull a new branch into SD

**Comment by mchaker** [comment]
@hlky please merge https://github.com/hlky/stable-diffusion-webui/pull/698

before merging `img2img-fix`

It fixes some color correction issues

**Comment by codedealer** [comment]
Solved in #736

**Comment by hashworks** [comment]
Are you sure this is fixed? I'm getting the same error on the current master when I go to "Image-to-Image Unified" -> "Advanced Editor" -> draw something -> save -> Type some prompt -> Generate.

```
Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

**Comment by codedealer** [comment]
@hashworks it's a different bug, refer to #811
