### ISSUE TITLE
[Bug]: Error on webui initial loading

### ISSUE THREAD

**Issue by sedetweiler** [sd-webui/stable-diffusion-webui#721]
### What happened?

All of the models are in place, but I get this and it just keeps on relaunching...

Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "scripts/webui.py", line 451, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 442, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 148, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "d:\stable-diffusion-webui\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "d:\stable-diffusion-webui\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\stable-diffusion-webui\ldm\models\diffusion\ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "d:\stable-diffusion-webui\ldm\models\autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\taming\modules\vqvae\quantize.py)
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 2

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xperia64** [comment]
This seems to have happened after the repo merge. Reverting to the environment.yaml from the old repo seems to get past this issue: https://github.com/sd-webui/stable-diffusion/blob/960b623acdef3b9a14454550cc68ad04e8d531a3/environment.yaml

**Comment by flowerdealer** [comment]
Yeah my installation got completely borked after pulling recently.

**Comment by blanham** [comment]
Replace `- taming-transformers>=0.0.11 `  with `- -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers` in environment.yaml

Seems like it's not happy with the version from pypi?

**Comment by sedetweiler** [comment]
Reverting as @xperia64 indicated at least has things running again.  Thank you!

**Comment by GRMrGecko** [comment]
Submitted pull request https://github.com/sd-webui/stable-diffusion-webui/pull/725

**Comment by GRMrGecko** [comment]
Fixed in https://github.com/sd-webui/stable-diffusion-webui/commit/b3e5a486dd0d7474baf979ea79174f1a2c1458a6
