### ISSUE TITLE
[Bug]: Conda envs: AttributeError: 'Request' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by aetherwu** [sd-webui/stable-diffusion-webui#770]
### What happened?

Console reports expection while running.
Looks like I am the only one who reports this error.

It might be caused by other packages, but please let me post it here for help.

[MemMon] Recording max memory usage...

 46%|█████████████████████████████████████▋                                            | 23/50 [00:09<00:07,  3.63it/s]

Task exception was never retrieved
future: <Task finished name='Task-82' coro=<Queue.process_event() done, defined at C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\event_queue.py:247> exception=AttributeError("'Request' object has no attribute '_json_response_data'")>
Traceback (most recent call last):
  File "C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\event_queue.py", line 267, in process_event
    "output": response.json,
  File "C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\utils.py", line 581, in json
    return self._json_response_data
AttributeError: 'Request' object has no attribute '_json_response_data'

### Version

0.0.1 (Default)

condalist:
requests                  2.25.1

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aetherwu** [comment]
It also happens when I apply ImageLab.
After error shows up, 'generate' or 'process' button stops working. 

Processing images...
Unloaded LDSR
Loaded GFPGAN
Unloaded GFPGAN
Loaded RealESGAN
Loaded GFPGAN
Done.
Task exception was never retrieved
future: <Task finished name='Task-127' coro=<Queue.process_event() done, defined at C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\event_queue.py:247> exception=AttributeError("'Request' object has no attribute '_json_response_data'")>
Traceback (most recent call last):
  File "C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\event_queue.py", line 267, in process_event
    "output": response.json,
  File "C:\Users\ssss\anaconda3\envs\ldm\lib\site-packages\gradio\utils.py", line 581, in json
    return self._json_response_data
AttributeError: 'Request' object has no attribute '_json_response_data'

**Comment by aetherwu** [comment]
I've tried reinstall with latest repo but issue remains.
