### ISSUE TITLE
[Bug]: Fixing faces using GFPGAN results in a RuntimeError (different types)

### ISSUE THREAD

**Issue by lthiet** [sd-webui/stable-diffusion-webui#772]
### What happened?

I tried to fix faces using GFPGAN, but it seems that there are errors regarding conflicting types.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Relevant log output

```shell
Loaded GFPGAN
Traceback (most recent call last):
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1826, in imgproc
    image = processGFPGAN(image,imgproc_gfpgan_strength)
  File "scripts/webui.py", line 1544, in processGFPGAN
    cropped_faces, restored_faces, restored_img = GFPGAN.enhance(np.array(image, dtype=np.uint8), has_aligned=False, only_center_face=False, paste_back=True)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lthiet/Code/stable-diffusion-webui/ultimate-stable-diffusion/src/gfpgan/gfpgan/utils.py", line 108, in enhance
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torchvision/models/_utils.py", line 63, in forward
    x = module(x)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/lthiet/miniconda3/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdBarho** [comment]
@lthiet this happens when GFPGAN is run on the CPU, does the problem persist if run on the GPU?

**Comment by lthiet** [comment]
No it doesn't, thanks!

**Comment by dudumaroja** [comment]
> @lthiet this happens when GFPGAN is run on the CPU, does the problem persist if run on the GPU?

is there a way to make work on cpu again?
