### ISSUE TITLE
[Bug]: AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'

### ISSUE THREAD

**Issue by kall666** [sd-webui/stable-diffusion-webui#783]
### What happened?

can't start up. please help

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "scripts/webui.py", line 451, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 442, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 148, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "g:\stable-diffusion-webui-master\src\latent-diffusion\ldm\util.py", line 78, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "g:\stable-diffusion-webui-master\src\latent-diffusion\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "g:\stable-diffusion-webui-master\src\latent-diffusion\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "g:\stable-diffusion-webui-master\src\latent-diffusion\ldm\util.py", line 78, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "g:\stable-diffusion-webui-master\src\latent-diffusion\ldm\util.py", line 86, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kall666** [comment]
fixed. close.

**Comment by ThomasDelteil** [comment]
I encounter this issue with latest master, how do I get the fix?

**Comment by kall666** [comment]
> I encounter this issue with latest master, how do I get the fix?

in my case , i copy the file in Idm folder to latent-diffusion\ldm
