### ISSUE TITLE
[Bug]: Img2Img not working in when using Advanced Editor

### ISSUE THREAD

**Issue by phil567** [sd-webui/stable-diffusion-webui#811]
### What happened?

When using Img2Img, after  using Advanced Editor, the UI will not generate when not in masking mode.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\ProgramData\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\ProgramData\miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\ProgramData\miniconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by otheivan** [comment]
Until it's fixed there is a work around.
1. Do the edits in the editor and save.
2. Select the mask tool and click the image (undo the mask if it masks anything, small circle arrow in the top right)
3. Switch back to crop.
4. Click Generate.

Not perfect but it works.

**Comment by ylsdamxssjxxdd** [comment]
same, when I click mask, it just loading and no response, and nothing error message
