### ISSUE TITLE
[Bug]: txt2img or img2img generate a green pi 

### ISSUE THREAD

**Issue by inspire-boy** [sd-webui/stable-diffusion-webui#834]
### What happened?

A bug happened!

![20220908220211](https://user-images.githubusercontent.com/112338987/189142406-6bb42551-6b59-44e4-a3d7-58d3290e0c3c.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Error loading LDSR:
Traceback (most recent call last):
  File "scripts/webui.py", line 384, in try_loading_LDSR
    LDSR = load_LDSR(checking=True) # TODO: Should try to load both models before giving up
  File "scripts/webui.py", line 299, in load_LDSR
    raise Exception("LDSR model not found at path "+model_path)
Exception: LDSR model not found at path ./src/latent-diffusion\experiments/pretrained_models\model.ckpt

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\pc\.conda\envs\ldm\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
Iteration: 1/1[MemMon] Recording max memory usage...


100%|████████████████████████████████████████████████████████████████████████████████| 50/50 [02:30<00:00,  3.01s/it]
[MemMon] Stopped recording.

[MemMon] Recording max memory usage...
Iteration: 1/1

Warning: Subprompt weights add up to zero. Discarding and using even weights instead.
100%|████████████████████████████████████████████████████████████████████████████████| 38/38 [01:51<00:00,  2.94s/it]
[MemMon] Stopped recording.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inspire-boy** [comment]
> 

Thank you very much, I change my way because I am 6G vram.

**Comment by Zenahr** [comment]
@taylor85345 is there a way to set no-half and full-precision when working with it programmatically?

**Comment by taylor85345** [comment]
> @taylor85345 is there a way to set no-half and full-precision when working with it programmatically?

@Zenahr Can you tell me how you are using it? I'm fairly new to all this too, and not really a programmer, but I might have an idea depending on what you mean.

**Comment by Zenahr** [comment]
@taylor85345 I switched to the official fork as that one allows me to set the flags I need to.

**Comment by slymeasy** [comment]
> Thank you very much, I change my way because I am 6G vram.

With Automatic1111's Stable Diffusion Pack it explains how you can create a preloader.bat file for those of us with 1660ti's or only 6GB of vram.

_set COMMANDLINE_ARGS=--precision full --no-half --medvram_
