### ISSUE TITLE
[Bug]: [Linux] GFPGAN fails with torch error.

### ISSUE THREAD

**Issue by taylor85345** [sd-webui/stable-diffusion-webui#852]
### What happened?

I set up the webui in Arch Linux following the steps detailed in the [Linux Automated Setup Guide](https://github.com/sd-webui/stable-diffusion-webui/wiki/Linux-Automated-Setup-Guide), downloading the gfpgan model from the mirror linked in the README. Any attempt to use GFPGAN fails with the following terminal output. The full traceback is below, but the key issue seems to be: `RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
--extra-models-cpu --inbrowser --optimized --no-half --precision-full
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1857, in imgproc
    image = processGFPGAN(image,imgproc_gfpgan_strength)
  File "scripts/webui.py", line 1575, in processGFPGAN
    cropped_faces, restored_faces, restored_img = GFPGAN.enhance(np.array(image, dtype=np.uint8), has_aligned=False, only_center_face=False, paste_back=True)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/taylor/Repos/stable-diffusion/stable-diffusion-webui/src/gfpgan/gfpgan/utils.py", line 108, in enhance
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 205, in detect_faces
    loc, conf, landmarks, priors = self.__detect_faces(image)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 156, in __detect_faces
    loc, conf, landmarks = self(inputs)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/facexlib/detection/retinaface.py", line 121, in forward
    out = self.body(inputs)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torchvision/models/_utils.py", line 63, in forward
    x = module(x)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/taylor/.conda/envs/lsd/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylor85345** [comment]
On further investigation, the problem seems to be the `--extra-models-cpu` flag. Disabling this flag allows GFPGAN to run properly. Based on my limited understanding, it seems that the input is being loaded to the GPU in spite of this flag, causing GFPGAN to fail when running on the CPU.

**Comment by dudumaroja** [comment]
windows (conda) here.. same problem here

**Comment by kiam001** [comment]
same problem
