### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'jsonmerge'

### ISSUE THREAD

**Issue by WoOox** [sd-webui/stable-diffusion-webui#854]
### What happened?

I followed the step by step tuto to get Stable diffusion WebUi on https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation

Everything works perfectly until I start webui.cmd, I always get the error about jsonmerge.
I tried to dowload it and put it in ldm>modules with the name jsonmerge but its doesnt change anything.

Any idea on how to solve this ?

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 57, in <module>
    import k_diffusion as K
  File "c:\users\name\stable-diffusion-webui\src\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "c:\users\name\stable-diffusion-webui\src\k-diffusion\k_diffusion\config.py", line 4, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'
Relauncher: Process is ending. Relaunching in 1s...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aupuma** [comment]
Same issue here :(

**Comment by jjisnow** [comment]
have you tried adding `jsonmerge` to the dependencies in `environment.yaml`? I think the conda system needs to be told to install it for it to be recognised in your virtual environment

**Comment by CptJackieSparrow** [comment]
So here's how i've solved it:
- open cmd and type pip install jsonmerge
- then i've encounter the second problem, which is no module called "frontend", pip install PyMuPDF should do the trick.

**Comment by CptJackieSparrow** [comment]
Same here.
Tried pip install jsonmerge, restarting.
Didn't make it unfortunately.

**Comment by CptJackieSparrow** [comment]
Anybody solved this issue? Working on it like hours rn

**Comment by CptJackieSparrow** [comment]
> have you tried adding `jsonmerge` to the dependencies in `environment.yaml`? I think the conda system needs to be told to install it for it to be recognised in your virtual environment

I did, nothing happens. It's just returning with the same error.

**Comment by jjisnow** [comment]
> ### What happened?
> I followed the step by step tuto to get Stable diffusion WebUi on https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation
> 
> Everything works perfectly until I start webui.cmd, I always get the error about jsonmerge. I tried to dowload it and put it in ldm>modules with the name jsonmerge but its doesnt change anything.
> 
> Any idea on how to solve this ?
> 
> ### Version
> 0.0.1 (Default)
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Where are you running the webui?
> Windows
> 
> ### Custom settings
> _No response_
> 
> ### Relevant log output
> ```shell
> Relauncher: Launching...
> Traceback (most recent call last):
>   File "scripts/webui.py", line 57, in <module>
>     import k_diffusion as K
>   File "c:\users\name\stable-diffusion-webui\src\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
>     from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
>   File "c:\users\name\stable-diffusion-webui\src\k-diffusion\k_diffusion\config.py", line 4, in <module>
>     from jsonmerge import merge
> ModuleNotFoundError: No module named 'jsonmerge'
> Relauncher: Process is ending. Relaunching in 1s...
> ```
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Can you check the starting or working directory? Maybe it's a case of starting in the wrong location

**Comment by CptJackieSparrow** [comment]
> 

what do you mean by starting directory?

**Comment by CptJackieSparrow** [comment]
by the way i've did exact steps on my win 10 machine (another PC) and it worked.
Not working and getting the same error on my  windows 11 pc.
Sandbox enviroment gives the same error either...

**Comment by jjisnow** [comment]
Try
`conda install jsonmerge
pip install jsonmerge`

**Comment by Aupuma** [comment]
> Try `conda install jsonmerge pip install jsonmerge`

If I write the command on the miniconda prompt there is the following error:
`PackagesNotFoundError: The following packages are not available from current channels:

  - jsonmerge

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

However, pip install jsonmerge does work. But the error with webui.cmd persists

**Comment by BinarySpike** [comment]
in `src/k-diffusion/k_diffusion/config.py`, line 4, if I comment out `from jsonmerge import merge` and change line 45 from `return merge(defaults, config)` to `return defaults #merge(defaults, config)`

It makes it further along.

**Comment by Garrett67** [comment]
I had the same problem, and ended up installing it from a different source found on Anaconda.org.
Try: conda install -c defusco jsonmerge

**Comment by BrassHead** [comment]
Installing jsonmerge just lead to getting more module not found errors.

I noticed that the onnx package had trouble installing because it could not find cmake (this error was much earlier in the output from setup_mac.sh). Homebrew puts cmake in /opt/homebrew/bin/ . The fix for me was to add a link in a more standard place with

`sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake`

and then restart terminal. After that setup_mac.sh ran to completion and the web_ui server started.

**Comment by castejon777** [comment]
Hey! Have same issue here in Windows 11... did you manage to solve the issue?

**Comment by ln167** [comment]
It thinks jsonmerge is installed already, but it isn't. The folder is in site-packages, but the files aren't. So delete the folder or do pip uninstall jsonmerge and just reinstall it with pip install jsonmerge.

**Comment by castejon777** [comment]
I already did that, I have figured out that when I execute webui-user.bat , it automatically deletes the jsonmerge folder.

**Comment by arieeeproject** [comment]
- Go to directory E:\SD Matic\stable-diffusion-webui\repositories\k-diffusion\k_diffusion
- Open file "config.py" with txt editor (i'm use notepad from windows)
- on line 6, delete "from jsonmerge import merge"
- save files
- just it

**Comment by chatods** [comment]
that absolutely works for me :))

> * Go to directory ...\stable-diffusion-webui\repositories\k-diffusion\k_diffusion
> * Open file "config.py" with txt editor (i'm use notepad from windows)
> * on line 6, delete "from jsonmerge import merge"
> * save files
> * just it

**Comment by chengqianlan** [comment]
> * Go to directory ...\stable-diffusion-webui\repositories\k-diffusion\k_diffusion
> * Open file "config.py" with txt editor (i'm use notepad from windows)
> * on line 6, delete "from jsonmerge import merge"
> * save files
> * just it


There is a merge on line 47, and deleting line 6 May cause problems with the program

**Comment by yiqiangjun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
