### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'websockets.datastructures'

### ISSUE THREAD

**Issue by Roalkege** [sd-webui/stable-diffusion-webui#859]
### What happened?

I followed the tuto on https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation
I used the webui.cmd. After installing everything the script crashed.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
C:\Users\user\miniconda3\envs\ldm\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\ldm\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\miniconda3\envs\ldm\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\user\miniconda3\envs\ldm\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\miniconda3\envs\ldm\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\config.py", line 471, in load
    ws_protocol_class = import_from_string(WS_PROTOCOLS[self.ws])
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\user\miniconda3\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\protocols\websockets\auto.py", line 17, in <module>
    from uvicorn.protocols.websockets.websockets_impl import WebSocketProtocol
  File "C:\Users\user\miniconda3\envs\ldm\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 9, in <module>
    from websockets.datastructures import Headers
ModuleNotFoundError: No module named 'websockets.datastructures'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Roalkege** [comment]
Fixed it with adding
    - websockets==10.3
    - websocket-client==1.4.1
   to the environment.yaml

But I think only websocket-client is needed.
