### ISSUE TITLE
[Bug]: RealESRGAN got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by mchaker** [sd-webui/stable-diffusion-webui#890]
### What happened?

Attempted to start streamlit UI by running:

```shell
export CURRENT_GPU_INDEX="4"; STREAMLIT_SERVER_PORT="786$CURRENT_GPU_INDEX" PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb:128" PYTHONPATH="." CUDA_VISIBLE_DEVICES="$CURRENT_GPU_INDEX" python3 -m streamlit run scripts/webui_streamlit.py
```

then the streamlit UI crashed - I received a stack trace/error when trying to press "Generate" in the streamlit UI.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
general:
    gpu: 0
    no_half: True
    precision: "full"
    update_preview: True
    update_preview_frequency: 1
```

### Relevant log output

```shell
Loading models.
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Loaded GFPGAN
2022-09-09 09:54:11.839 __init__() got an unexpected keyword argument 'device', retrying in 0 seconds...
Loading models.
GFPGAN already loaded
2022-09-09 09:54:12.102 __init__() got an unexpected keyword argument 'device', retrying in 0 seconds...
Loading models.
GFPGAN already loaded
2022-09-09 09:54:12.364 __init__() got an unexpected keyword argument 'device', retrying in 0 seconds...
Loading models.
GFPGAN already loaded
2022-09-09 09:54:12.625 __init__() got an unexpected keyword argument 'device', retrying in 0 seconds...
Loading models.
GFPGAN already loaded
2022-09-09 09:54:12.888 Uncaught app exception
Traceback (most recent call last):
  File "/home/maintenance/.local/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/data/github/mchaker/sd-webui-dev/scripts/webui_streamlit.py", line 2169, in <module>
    layout()
  File "/data/github/mchaker/sd-webui-dev/scripts/webui_streamlit.py", line 1857, in layout
    load_models(False, use_GFPGAN, use_RealESRGAN, RealESRGAN_model, CustomModel_available, custom_model)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/maintenance/.local/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/maintenance/.local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/data/github/mchaker/sd-webui-dev/scripts/webui_streamlit.py", line 146, in load_models
    st.session_state["RealESRGAN"] = load_RealESRGAN(RealESRGAN_model)
  File "/data/github/mchaker/sd-webui-dev/scripts/webui_streamlit.py", line 475, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not defaults.general.no_half, device=torch.device(f'cuda:{defaults.general.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
Have you updated your environment recently?
I remember there was a change somewhere on one library that changed this.

**Comment by mchaker** [comment]
Ah, I have not updated RealESRGAN. I'll try that

**Comment by mchaker** [comment]
Updating RealESRGAN (`pip install -U realesrgan`) did not work
