### ISSUE TITLE
[Bug]: Invalid conda environment - Windows

### ISSUE THREAD

**Issue by JerzyKruszewski** [sd-webui/stable-diffusion-webui#897]
### What happened?

I tried to follow https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation 
But something is wrong with my conda environment.
When running webui.cmd I get exceptions about invalid conda env.
I already had it installed from https://github.com/hlky/stable-diffusion and it was working correctly

OS: Windows 10 Home 64bit
Conda version: 4.12.0

conda info --envs output:
```
(base) D:\TextToImageAI\stable-diffusion-webui>conda info --envs
# conda environments:
#
base                  *  D:\Users\Admin\miniconda3
ldm                      D:\Users\Admin\miniconda3\envs\ldm
ldo                      D:\Users\Admin\miniconda3\envs\ldo


(base) D:\TextToImageAI\stable-diffusion-webui>
```

my environment.yaml
```
name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - gradio==3.1.6
    - accelerate==0.12.0
    - pynvml==11.4.1
    - basicsr>=1.3.4.0
    - facexlib>=0.2.3
    - python-slugify>=6.1.2
    - streamlit>=1.12.2
    - retry>=0.9.2
    - -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP#egg=clip
    - -e git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN
    - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
    - -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion
    - -e .
```

I tried:
- changing env name to ldo in evnvironment.yaml
- removing space between property name and value `name: ldm` => `name:ldm`
- coping evnvironment.yaml from previous project into webui one

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Environment name is set as  ldm as per environment.yaml
anaconda3/miniconda3 detected in D:\Users\Admin\miniconda3

CondaValueError: Invalid environment name: ' ldm'
  Characters not allowed: ('/', ' ', ':', '#')


CondaValueError: Invalid environment name: ' ldm'
  Characters not allowed: ('/', ' ', ':', '#')

Could not find conda environment:  ldm
You can list all discoverable environments with `conda info --envs`.

Relauncher: Launching...
Traceback (most recent call last):
  File "D:\TextToImageAI\stable-diffusion-webui\scripts\webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
Traceback (most recent call last):
  File "D:\TextToImageAI\stable-diffusion-webui\scripts\relauncher.py", line 64, in <module>
    time.sleep(1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JerzyKruszewski** [comment]
Problem still exist with conda 4.14.0

**Comment by codedealer** [comment]
I suggest removing the environment and creating a new one from yaml so that you can be sure you're starting from the clean slate.

**Comment by muyufan** [comment]
just edit webui.cmd, remove line 4-8

and with below line

set conda_env_name=ldm

**Comment by codedealer** [comment]
Was this fixed in #894 ? 🤔
