### ISSUE TITLE
[Bug]: OSError: It looks like the config file at 'C:\Users\.cache\huggingface\transformers\' is not a valid JSON file.

### ISSUE THREAD

**Issue by andzejsp** [sd-webui/stable-diffusion-webui#919]
### What happened?

Everything worked on the hlky branch, today i cloned this repo, thinking it will be even better but cant even launch it.
Windows 10.
miniconda

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
#     $ conda activate ldm
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\configuration_utils.py", line 650, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\configuration_utils.py", line 734, in _dict_from_json_file
    return json.loads(text)
  File "E:\miniconda3\envs\ldm\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "E:\miniconda3\envs\ldm\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\miniconda3\envs\ldm\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/webui.py", line 453, in <module>
    model, device,config = load_SD_model()
  File "scripts/webui.py", line 444, in load_SD_model
    model = load_model_from_config(config, opt.ckpt)
  File "scripts/webui.py", line 150, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "j:\localrepos\stable-diffusion-webui\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "j:\localrepos\stable-diffusion-webui\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "j:\localrepos\stable-diffusion-webui\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "j:\localrepos\stable-diffusion-webui\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "j:\localrepos\stable-diffusion-webui\ldm\modules\encoders\modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\miniconda3\envs\ldm\lib\site-packages\transformers\configuration_utils.py", line 652, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'C:\Users\redacted/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.
Relauncher: Process is ending. Relaunching in 1s...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qualzz** [comment]
I have exactly the same issue. But I don't know if it's after adding the files from the "text-inversion- repo or not

**Comment by fbkgs** [comment]
> I have exactly the same issue. But I don't know if it's after adding the files from the "text-inversion- repo or not

Can't be, I did a fresh install and have the same problem

**Comment by codedealer** [comment]
It just appeared. Not sure it was introduced by this repo?

**Comment by Buckzor** [comment]
So weird, I was just searching how to fix this just now and saw you posted 1 min ago. Same problem, fresh install. Tried deleting envs, cache files, still same error.

**Comment by andzejsp** [comment]
i confirmed the old repo from hlky is borked too.. its not launching anymore :(

**Comment by fbkgs** [comment]
Looks like the last functional repo history was from 19 hours ago

**Comment by AdriaandeJongh** [comment]
If you open up the file in question, you will find two lines in it that contain the following: `"projection_dim": 768,` 

Remove the comma after 768 in both places and the launch script continues. no idea what it causing these invalid commas to appear.

**Comment by Chito-Chito-Chito** [comment]
Occurring on multiple projects; I cloned AUTOMATIC1111s version (https://github.com/AUTOMATIC1111/stable-diffusion-webui) this morning and it's happening there too.

**Comment by codedealer** [comment]
It's hugging face's transformers which everyone uses.

**Comment by Buckzor** [comment]
> 

Which file are you referring to?

**Comment by AdriaandeJongh** [comment]
Open the file at the folowing path: `C:\Users\redacted\.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142`

Remove the trailing comma's after `"projection_dim": 768`

**Comment by andzejsp** [comment]
> Open the file at the folowing path: `C:\Users\redacted\.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142`
> 
> Remove the trailing comma's after `"projection_dim": 768`

didnt help, same error

**Comment by ThioJoe** [comment]
> > Open the file at the folowing path: `C:\Users\redacted\.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142`
> > Remove the trailing comma's after `"projection_dim": 768`
> 
> didnt help, same error

There are actually two places you need to remove the comma. Any time it is the last item within a set of brackets

**Comment by codedealer** [comment]
There is another trailing comma on **line 170**

**Comment by andzejsp** [comment]
better solution is to paste the json into VS code and it will show what places error is :D

Thanks, for help, there are actually 3 places with "projection_dim": 768 but you need to fix the ones that are at the end of the {  block }

**Comment by brnorman** [comment]
Thanks - removing the commas fixed the problem for me

**Comment by erojaro** [comment]
I have the same error but json file contains only a link to hugface.co so i cannot delete the commas.

**Comment by rardias** [comment]
> So, what should I do if I'm on colab?

Wondering the same thing, since we haven't got the ability to edit, donwload/upload this specific file...

**Comment by Anaphylaxis** [comment]
> I have the same error but json file contains only a link to hugface.co so i cannot delete the commas.
here is the fixed version, i dont know how yours is setup but this works for my hlky webui
`{
  "_name_or_path": "clip-vit-large-patch14/",
  "architectures": [
    "CLIPModel"
  ],
  "initializer_factor": 1.0,
  "logit_scale_init_value": 2.6592,
  "model_type": "clip",
  "projection_dim": 768,
  "text_config": {
    "_name_or_path": "",
    "add_cross_attention": false,
    "architectures": null,
    "attention_dropout": 0.0,
    "bad_words_ids": null,
    "bos_token_id": 0,
    "chunk_size_feed_forward": 0,
    "cross_attention_hidden_size": null,
    "decoder_start_token_id": null,
    "diversity_penalty": 0.0,
    "do_sample": false,
    "dropout": 0.0,
    "early_stopping": false,
    "encoder_no_repeat_ngram_size": 0,
    "eos_token_id": 2,
    "finetuning_task": null,
    "forced_bos_token_id": null,
    "forced_eos_token_id": null,
    "hidden_act": "quick_gelu",
    "hidden_size": 768,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "initializer_factor": 1.0,
    "initializer_range": 0.02,
    "intermediate_size": 3072,
    "is_decoder": false,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "layer_norm_eps": 1e-05,
    "length_penalty": 1.0,
    "max_length": 20,
    "max_position_embeddings": 77,
    "min_length": 0,
    "model_type": "clip_text_model",
    "no_repeat_ngram_size": 0,
    "num_attention_heads": 12,
    "num_beam_groups": 1,
    "num_beams": 1,
    "num_hidden_layers": 12,
    "num_return_sequences": 1,
    "output_attentions": false,
    "output_hidden_states": false,
    "output_scores": false,
    "pad_token_id": 1,
    "prefix": null,
    "problem_type": null,
    "projection_dim" : 768,
    "pruned_heads": {},
    "remove_invalid_values": false,
    "repetition_penalty": 1.0,
    "return_dict": true,
    "return_dict_in_generate": false,
    "sep_token_id": null,
    "task_specific_params": null,
    "temperature": 1.0,
    "tie_encoder_decoder": false,
    "tie_word_embeddings": true,
    "tokenizer_class": null,
    "top_k": 50,
    "top_p": 1.0,
    "torch_dtype": null,
    "torchscript": false,
    "transformers_version": "4.16.0.dev0",
    "use_bfloat16": false,
    "vocab_size": 49408
  },
  "text_config_dict": {
    "hidden_size": 768,
    "intermediate_size": 3072,
    "num_attention_heads": 12,
    "num_hidden_layers": 12,
    "projection_dim": 768
  },
  "torch_dtype": "float32",
  "transformers_version": null,
  "vision_config": {
    "_name_or_path": "",
    "add_cross_attention": false,
    "architectures": null,
    "attention_dropout": 0.0,
    "bad_words_ids": null,
    "bos_token_id": null,
    "chunk_size_feed_forward": 0,
    "cross_attention_hidden_size": null,
    "decoder_start_token_id": null,
    "diversity_penalty": 0.0,
    "do_sample": false,
    "dropout": 0.0,
    "early_stopping": false,
    "encoder_no_repeat_ngram_size": 0,
    "eos_token_id": null,
    "finetuning_task": null,
    "forced_bos_token_id": null,
    "forced_eos_token_id": null,
    "hidden_act": "quick_gelu",
    "hidden_size": 1024,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "image_size": 224,
    "initializer_factor": 1.0,
    "initializer_range": 0.02,
    "intermediate_size": 4096,
    "is_decoder": false,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "layer_norm_eps": 1e-05,
    "length_penalty": 1.0,
    "max_length": 20,
    "min_length": 0,
    "model_type": "clip_vision_model",
    "no_repeat_ngram_size": 0,
    "num_attention_heads": 16,
    "num_beam_groups": 1,
    "num_beams": 1,
    "num_hidden_layers": 24,
    "num_return_sequences": 1,
    "output_attentions": false,
    "output_hidden_states": false,
    "output_scores": false,
    "pad_token_id": null,
    "patch_size": 14,
    "prefix": null,
    "problem_type": null,
    "projection_dim" : 768,
    "pruned_heads": {},
    "remove_invalid_values": false,
    "repetition_penalty": 1.0,
    "return_dict": true,
    "return_dict_in_generate": false,
    "sep_token_id": null,
    "task_specific_params": null,
    "temperature": 1.0,
    "tie_encoder_decoder": false,
    "tie_word_embeddings": true,
    "tokenizer_class": null,
    "top_k": 50,
    "top_p": 1.0,
    "torch_dtype": null,
    "torchscript": false,
    "transformers_version": "4.16.0.dev0",
    "use_bfloat16": false
  },
  "vision_config_dict": {
    "hidden_size": 1024,
    "intermediate_size": 4096,
    "num_attention_heads": 16,
    "num_hidden_layers": 24,
    "patch_size": 14,
    "projection_dim": 768
  }
}
`

**Comment by codedealer** [comment]
> I have the same error but json file contains only a link to hugface.co so i cannot delete the commas.

@erojaro the file you're looking for is the one above the one you're opening. The file in question doesn't have an extension but you can still open it in text editor and apply the changes.

**Comment by bilter1001** [comment]
I have the same error
file: 9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142.json
content：
{"url": "https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json", "etag": "\"fd2437b2c4b8d8c50bf8ce1cde84c286ed279f6c\""}

**Comment by bobboff** [comment]
@Anaphylaxis Thank you, That fixed it for me.

So how has this error suddenly appeared then?

**Comment by andzejsp** [comment]
> @Anaphylaxis Thank you, That fixed it for me.
> 
> So how has this error suddenly appeared then?

im guessing someone with FAT32 fingers misspressed some buttons

**Comment by bilter1001** [comment]
> Open the file at the folowing path: `C:\Users\redacted\.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142`
> 
> Remove the trailing commas after `"projection_dim": 768` after both invalid instances.
@Anaphylaxis  Thank you, it works.
So how has this error suddenly appeared then?

**Comment by iChristGit** [comment]
How can it break for everybody (ive tried 3 different builds) and break without any update? does it mean that even if you have it locally it can break or changed without you knowing or willingly update? seems weird to me

**Comment by evanjs** [comment]
Open PR for upstream issue:
https://huggingface.co/openai/clip-vit-large-patch14/discussions/3

**Comment by Batman313v** [comment]
The hugginface file has been fixed. Builds appear to be working again

**Comment by mr555ru** [comment]
I have opened https://github.com/sd-webui/stable-diffusion-webui/discussions/938 feature request in order to ensure that users would be able to prevent any such bugs from happening again
