### ISSUE TITLE
[Bug]: img2img failing

### ISSUE THREAD

**Issue by rethink-studios** [sd-webui/stable-diffusion-webui#948]
### What happened?

I created a duplicate image of your tutorial, ( 2 circles over white and prompt: An owl perched, etc) and this is the error:

Traceback (most recent call last):
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

How can I fix? 

Thanks in advance!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
Nope
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\rethink\anaconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudumaroja** [comment]
know bug.. go to mask.. draw something then go back to crop/uncrop and try again

**Comment by sedetweiler** [comment]
Even clicking on "mask" makes the sample image gray with no method to reset it or to upload.

**Comment by codedealer** [comment]
Does it fail on `dev` branch for you as well?

**Comment by rethink-studios** [comment]
Thanks for the help, everyone!

@codedealer 
Installed dev using model 1.0 of SD and work, albeit image quality isn't there just yet.
![image](https://user-images.githubusercontent.com/60104539/189497909-909e817a-4c9d-41a0-bd23-a5275ac59466.png)

Am I using the incorrect models or samplers?

**Comment by codedealer** [comment]
I’m not sure what do you mean about model 1.0? The current version of weights is 1.4. 
the important thing is that it works

**Comment by rethink-studios** [comment]
@codedealer
My mistake, you are correct.

**Comment by sedetweiler** [comment]
> Does it fail on `dev` branch for you as well?

yes, it fails in dev as well.

**Comment by codedealer** [comment]
@sedetweiler please describe steps to reproduce then.
