### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sibernewf** [sd-webui/stable-diffusion-webui#958]
### What happened?

When going to the Image-to-Image unified tab.
I kept the default image in the left as the input image.
Clicked the 'generate' button. and the following output appeared in my terminal:

Traceback (most recent call last):
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Custom settings

```shell
I am using default settings
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\bloke\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
There is no default image on Image2Image tab. Update before opening an issue.
