### ISSUE TITLE
[Bug]: Img2Img No Longer Works

### ISSUE THREAD

**Issue by Gushousekai195** [sd-webui/stable-diffusion-webui#973]
### What happened?

I tried to use Img2Img but it doesn’t work. I’m running the colab on my iPad Air 3.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Safari

### Where are you running the webui?

Colab

### Relevant log output

```shell
Iteration: 1/1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1288, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 819, in process_images
    samples_ddim = func_sample(init_data=init_data, x=x, conditioning=c, unconditional_conditioning=uc, sampler_name=sampler_name)
  File "scripts/webui.py", line 1194, in sample
    xi = x0 + noise
RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by insectatorious** [comment]
What are the dimensions of the input image? I get this error when it's not a multiple of 64.

**Comment by Gushousekai195** [comment]
> What are the dimensions of the input image? I get this error when it's not a multiple of 64.

It didn’t have to be a multiple of 64 before! And it doesn’t have to be a multiple of 64 on similar colabs.

**Comment by heyitsguay** [comment]
I experienced the same behavior trying to work on an 896x896 image, which is divisible by 64

**Comment by hilmiyafia** [comment]
I have the same issue

![Error](https://user-images.githubusercontent.com/56539775/189499765-43e74bd3-25d4-4356-8914-7ec6bf465f6a.png)

**Comment by Gushousekai195** [comment]
Where's @altryne?  @hlky?

**Comment by flotos** [comment]
I had this issue when using in input image no *exactly* in the same size as the output, in a previous version. I don't have it anymore though. You could try editing the input image to be the same as output to see if that changes anything, could help investigate this bug.

**Comment by heyitsguay** [comment]
I had this issue with input and output images of the same size.

**Comment by akino-germany** [comment]
this line: https://github.com/sd-webui/stable-diffusion-webui/blob/pin-for-colab/webui.py#L1138 needs to be changed to 
image = image.convert("RGB")
