### ISSUE TITLE
[Bug]: DDIM and PLSM Fail to render a prompt at 9 Sampling Steps. 8 OK 10 OK 11 OPK 30 OK but 9 fails

### ISSUE THREAD

**Issue by osi1880vr** [sd-webui/stable-diffusion-webui#981]
### What happened?

When I try to render a prompt with 9 sampling steps fopr DDIM and PLSM it fails with this homongus error message:
see below in the log part

8 OK 10 OK all the other samplers OK. I dont know if this is me or its a bug. It comes now and is reproduceable.
Before I had some hickup with my Python after I installed VS2022 to see if I could also run Dalle. Removed anything and deleted files by hand. Nothing helps at Sampling Steps 9. Its easy to work around =) But still very strange as a bug

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Exception processing job JobInfo(inputs=('something', 9, 'DDIM', [1, 2, 3, 4, 5], 'RealESRGAN_x4plus', 0, 1, 1, 7.5, '', 512, 512, None, 0, ''), func=<function txt2img at 0x000002771D8F28B0>, session_key='"a5e4411f41ca4c36bc692c71f8df9f7e"', job_token=0, images=[], should_stop=<threading.Event object at 0x000002773B4F6A30>, job_status='Error: index 1000 is out of bounds for dimension 0 with size 1000', finished=False, removed_output_idxs=[0]): index 1000 is out of bounds for dimension 0 with size 1000
Traceback (most recent call last):
  File "d:\stablediffusion\stable-diffusion-webui\frontend\job_manager.py", line 232, in _call_func
    outputs = job_info.func(*job_info.inputs, job_info=job_info)
  File "scripts/webui.py", line 1142, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 938, in process_images
    samples_ddim = func_sample(init_data=init_data, x=x, conditioning=c, unconditional_conditioning=uc, sampler_name=sampler_name)
  File "scripts/webui.py", line 1138, in sample
    samples_ddim, _ = sampler.sample(S=ddim_steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=cfg_scale, unconditional_conditioning=unconditional_conditioning, eta=ddim_eta, x_T=x)
  File "C:\Users\myUserName\.conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "d:\stablediffusion\stable-diffusion-webui\ldm\models\diffusion\ddim.py", line 90, in sample
    self.make_schedule(ddim_num_steps=S, ddim_eta=eta, verbose=verbose)
  File "d:\stablediffusion\stable-diffusion-webui\ldm\models\diffusion\ddim.py", line 44, in make_schedule
    ddim_sigmas, ddim_alphas, ddim_alphas_prev = make_ddim_sampling_parameters(alphacums=alphas_cumprod.cpu(),
  File "d:\stablediffusion\stable-diffusion-webui\ldm\modules\diffusionmodules\util.py", line 65, in make_ddim_sampling_parameters
    alphas = alphacums[ddim_timesteps]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

Traceback (most recent call last):
  File "C:\Users\myUserName\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\myUserName\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\Users\osiwo\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "C:\Users\osiwo\.conda\envs\ldm\lib\site-packages\gradio\components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "C:\Users\osiwo\.conda\envs\ldm\lib\site-packages\gradio\components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: 'a65ea8d513024609ad143744be69bce4'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by osi1880vr** [comment]
Seems to be like a know bug, its not just 9 its some other values too.
More detail can be found here:
https://pullanswer.com/questions/indexerror-index-1000-is-out-of-bounds-for-dimension-0-with-size-1000

**Comment by osi1880vr** [comment]
To fix this issue, one can change the make_ddim_timesteps function in ldm/moduzles/diffusionmodules/util.py

def make_ddim_timesteps(ddim_discr_method, num_ddim_timesteps, num_ddpm_timesteps, verbose=True):
    if ddim_discr_method == 'uniform':
        c = num_ddpm_timesteps // num_ddim_timesteps
        ddim_timesteps = np.asarray(list(range(0, num_ddpm_timesteps, c)))
    elif ddim_discr_method == 'quad':
        ddim_timesteps = ((np.linspace(0, np.sqrt(num_ddpm_timesteps * .8), num_ddim_timesteps)) ** 2).astype(int)
    else:
        raise NotImplementedError(f'There is no ddim discretization method called "{ddim_discr_method}"')

    # assert ddim_timesteps.shape[0] == num_ddim_timesteps
    # add one to get the final alpha values right (the ones from first scale to data during sampling)
    #steps_out = ddim_timesteps + 1   
    steps_out = np.where(ddim_timesteps != 999, ddim_timesteps+1, ddim_timesteps)
    if verbose:
        print(f'Selected timesteps for ddim sampler: {steps_out}')
    return steps_out


we disable the original steps_out = = ddim_timesteps + 1   line. The error is caused by a value of 1000 so +1 can create this...
Effect is 9 steps in ddim become magicaly 10 steps, 107 steps become magicaly 112 steps. it somehow jumps the error causing number of steps. 
For now this somehow fixes the issue. Someone much much more inteligent than me could fix the real issue below the surface ;)
