### ISSUE TITLE
[Bug]: GFPGAN is broken

### ISSUE THREAD

**Issue by levicki** [sd-webui/stable-diffusion-webui#986]
### What happened?

When you use img2img and check "Fix faces using GFPGAN" after the image is generated in the console window it is visible that the script is trying to download a file:

```
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth" to C:\PROGRAMS\SDGUI\gfpgan\weights\parsing_parsenet.pth
```
My installation folder is `C:\PROGRAMS\SDGUI`.

Note that it is not downloading the file into `.src/gfpgan/weights` or `.src/gfpgan/gfpgan/weights` but into `./gfpgan/weights` folder instead. Download is failing with some bogus SSL error:
```
Exception processing job JobInfo(inputs=('<censored>', 'Crop', 0, 3, 50, 'k_euler_a', [1, 4, 6, 10], 'RealESRGAN_x4plus', 1, 5, 0.75, None, 512, 512, 0, <PIL.Image.Image image mode=RGBA size=768x576 at 0x1CBA2522A90>, None, None), func=<function img2img at 0x000001CB8F9E2D30>, session_key='"fc167866cdea4f7cb03b194dd470e792"', job_token=0, images=[], should_stop=<threading.Event object at 0x000001CBA25227F0>, job_status='Error: [ASN1] nested asn1 error (_ssl.c:4145)', finished=False, removed_output_idxs=[0]): [ASN1] nested asn1 error (_ssl.c:4145)
```
I tried updating `certifi` package and when I test the https from python using `import requests` it results in `200 OK` so I have no idea why the download fails.

Traceback:
```
Traceback (most recent call last):
  File "c:\programs\sdgui\frontend\job_manager.py", line 232, in _call_func
    outputs = job_info.func(*job_info.inputs, job_info=job_info)
  File "scripts/webui.py", line 1256, in img2img
    ModelLoader(['GFPGAN'],True,False)
  File "scripts/webui.py", line 1935, in ModelLoader
    global_vars[m] = load_GFPGAN()
  File "scripts/webui.py", line 324, in load_GFPGAN
    instance = GFPGANer(model_path=model_path, upscale=1, arch='clean', channel_multiplier=2, bg_upsampler=None, device=torch.device(f'cuda:{opt.gpu}'))
  File "c:\programs\sdgui\src\gfpgan\gfpgan\utils.py", line 76, in __init__
    self.face_helper = FaceRestoreHelper(
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 103, in __init__
    self.face_parse = init_parsing_model(model_name='parsenet', device=self.device, model_rootpath=model_rootpath)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\facexlib\parsing\__init__.py", line 18, in init_parsing_model
    model_path = load_file_from_url(
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\facexlib\utils\misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\torch\hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\urllib\request.py", line 1319, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\http\client.py", line 1394, in __init__
    context = ssl._create_default_https_context()
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\ssl.py", line 750, in create_default_context
    context.load_default_certs(purpose)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\ssl.py", line 574, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\ssl.py", line 566, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: [ASN1] nested asn1 error (_ssl.c:4145)
```
And another traceback:
```
Traceback (most recent call last):
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\gradio\components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "C:\PROGRAMS\Miniconda3\envs\ldm\lib\site-packages\gradio\components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: 'e09a6404b64b41eb9d058e435b22f965'
```

Furthermore, there is this code in webui.py:
```
default=('./src/gfpgan' if os.path.exists('./src/gfpgan') else './GFPGAN'))
```
In my case `./src/gfpgan` exists and also has a subfolder `gfpgan` which contains subfolder `weights` and `README.md` which says that weights files should be put there so one of those three things is incorrect -- either the default path is wrong, or the nested `gfpgan` folder is wrong, or the `README.md` in `weights` subfolder is wrong.

Please fix.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by levicki** [comment]
Fixed by updating, and following updated instructions.
