### ISSUE TITLE
[Bug]: [WinError 127] can't find procedure

### ISSUE THREAD

**Issue by DiegoRRR** [sd-webui/stable-diffusion-webui#987]
### What happened?

A bug happened while running webui.cmd

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 57, in <module>
    import k_diffusion as K
  File "d:\bordel\apps\ai\stable-diffusion\src\k-diffusion\k_diffusion\__init__.
py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, model
s, sampling, utils
  File "d:\bordel\apps\ai\stable-diffusion\src\k-diffusion\k_diffusion\augmentat
ion.py", line 6, in <module>
    from skimage import transform
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\skimage\__init__.py
", line 157, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\skimage\util\__init
__.py", line 9, in <module>
    from .apply_parallel import apply_parallel
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\skimage\util\apply_
parallel.py", line 3, in <module>
    from .._shared.utils import channel_as_last_axis, deprecate_multichannel_kwa
rg
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\skimage\_shared\uti
ls.py", line 8, in <module>
    import scipy
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\scipy\__init__.py",
 line 134, in <module>
    from scipy.__config__ import show as show_config
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\site-packages\scipy\__config__.py
", line 13, in <module>
    os.add_dll_directory(extra_dll_dir)
  File "C:\ProgramData\Miniconda3\envs\ldm\lib\os.py", line 1109, in add_dll_dir
ectory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 127] La procédure spécifiée est introuvable: 'C:\\ProgramData
\\Miniconda3\\envs\\ldm\\lib\\site-packages\\scipy\\.libs'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prsyahmi** [comment]
I think you have wrong scipy version. Have you tried recreated the environment and update the environment?
